<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-android</TargetFramework>
        <SupportedOSPlatformVersion>27</SupportedOSPlatformVersion>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <ApplicationId>com.MainVerte.MainVerte</ApplicationId>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <AndroidGenerateLayoutBindings>true</AndroidGenerateLayoutBindings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.4" />
        <PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.8.9.3" />
        <PackageReference Include="Xamarin.AndroidX.RecyclerView" Version="1.4.0.6" />
        <PackageReference Include="Xamarin.Google.Android.Material" Version="1.14.0.6" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\MainVerte.Core\MainVerte.Core.csproj" />
    </ItemGroup>
    <PropertyGroup>
        <WarningsAsErrors>$(WarningsAsErrors);RS0030</WarningsAsErrors>
    </PropertyGroup>
</Project>
